apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.azure.blobstorage
  version: v1
  metadata:
  - name: accountName
    secretKeyRef:
      name: dapr-secrets
      key: storage-account-name
  - name: accountKey
    secretKeyRef:
      name: dapr-secrets
      key: storage-account-key
  - name: containerName
    value: "test"
auth:
  secretStore: dapr-secrets
