apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-queue-auth
spec:
  secretTargetRef:                          # Optional.
  - parameter: connection           # Required - Defined by the scale trigger
    name: keda-secrets           # Required.
    key: azure-storage-connectionstring   # Required.
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-queue-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: daprmvc
  pollingInterval:  30                               # Optional. Default: 30 seconds
  cooldownPeriod:   300                              # Optional. Default: 300 seconds
  idleReplicaCount: 1                                # Optional. Must be less than minReplicaCount
  minReplicaCount:  2                                # Optional. Default: 0
  maxReplicaCount:  100                              # Optional. Default: 100
  triggers:
  - type: azure-queue
    metadata:
      # Required
      queueName: daprtest
      # Optional, required when pod identity is used
      accountName: mfdaprstore01
      # Optional: connection OR authenticationRef that defines connection
      # connectionFromEnv: STORAGE_CONNECTIONSTRING # Default: AzureWebJobsStorage. Reference to a connection string in deployment
      # or authenticationRef as defined below
      #
      # Optional
      queueLength: "2" # default 5
      cloud: AzurePublicCloud
    authenticationRef:
        name: azure-queue-auth # authenticationRef would need either podIdentity or define a connection parameter